name: Librarian.Lou
favicon: null
layout_spectrum: 0.3617081381380558
typography_spectrum: 0.31686900882050395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.15697873337194324
  lightness: 0.3493298040702939
  saturation: 0.15823168773204088
  rhythmicContrast: 0.22192658437415957
purpose: []
